In [1]:
import pandas as pd

In [2]:
df1 = pd.read_json("../chunks/chunk_1.json")

In [3]:
df2 = pd.read_json("../chunks/chunk_2.json")
df3 = pd.read_json("../chunks/chunk_3.json")
df4 = pd.read_json("../chunks/chunk_4.json")
df5 = pd.read_json("../chunks/chunk_5.json")
df6 = pd.read_json("../chunks/chunk_6.json")
df7 = pd.read_json("../chunks/chunk_7.json")
df8 = pd.read_json("../chunks/chunk_8.json")
df9 = pd.read_json("../chunks/chunk_9.json")
df10 = pd.read_json("../chunks/chunk_10.json")

In [6]:
df1

,_id,make,model,trim,bodyType,cylinders,year,insureType,chassisNumber,price,...,transmission,autoDataPrice,engineCapacity,maxValue,minValue,mortgageBankName,regCardNameAr,applicantId,userId,carImages
0,{'$oid': '68592fc0f32ddc587c27aafb'},TOYOTA,HIACE,DX,Mini Bus High Roof,4,2015,thirdparty,JTFHX02P7F0094323,48400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '685935005d8bb5f0ab18a181'},TOYOTA,HIACE,DX,Mini Bus High Roof,4,2015,thirdparty,JTFHX02P7F0094323,48400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '685944995d8bb5f0ab18bafc'},TOYOTA,HILUX,DL,Pick Up Double Cab,4,2015,comprehensive,JTFHXDGP7F0094373,37800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '68596237e6bdae3db611dab9'},INFINITI,QX50,LUXE STYLE,SUV,4,2024,thirdparty,JN1ASNYC3PU200564,142000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '685bb1456ce98addfc08ed19'},BMW,420I,M SPORT PREMIUM,COUPE,4,2024,thirdparty,WBA11AP04RCR41747,156500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167495,{'$oid': '6909af719d8fc5c1c4223f8d'},NISSAN,URVAN,STD,Mini Bus,4,2007,thirdparty,JN6FE54SX7X438060,7700,...,NaN,7700.0,None,0.0,0.0,NaN,محطة ماجستي لخدمات السيارات,NaN,NaN,[]
167496,{'$oid': '6909af719d8fc5c1c4223fd3'},TOYOTA,RAV4,BASE,SUV,4,2010,thirdparty,2T3BF4DVXAW069893,17000,...,NaN,17000.0,None,0.0,0.0,NaN,نیتو بلا راجیندر کومار,NaN,NaN,[]
167497,{'$oid': '6909af72313f806a5690565e'},NISSAN,ALTIMA,SL,SEDAN,4,2019,thirdparty,1N4BL4EVXKC170000,55500,...,NaN,55500.0,None,0.0,0.0,NaN,يعقوب خالد خليل عياد,NaN,NaN,[]
167498,{'$oid': '6909af73c1f64147c4d8d744'},TOYOTA,LAND CRUISER,VXR,SUV,6,2021,thirdparty,JTMHY05J8M4095953,211200,...,NaN,211200.0,None,0.0,0.0,NaN,مسفر محمد عايض حنيف الاحبابي,NaN,NaN,[]
167499,{'$oid': '6909af79c1f64147c4d8d7f4'},NISSAN,ALTIMA,SV,SEDAN,4,2019,thirdparty,1N4BL4A98KC161692,53200,...,NaN,53200.0,None,0.0,0.0,NaN,محمد راشد محمد راشد الحساني,NaN,NaN,[]

In [4]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10], ignore_index=True)

In [5]:
df

,_id,make,model,trim,bodyType,cylinders,year,insureType,chassisNumber,price,...,carImages,tradeLicenseName,autoDataResponse,mortgageDocumentDate,bodyTypeCode,vehicleMileage,ocrRCVerified,ocrVCCVerified,ocrNCCVerified,ocrPassingPaperVerified
0,{'$oid': '68592fc0f32ddc587c27aafb'},TOYOTA,HIACE,DX,Mini Bus High Roof,4,2015,thirdparty,JTFHX02P7F0094323,48400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '685935005d8bb5f0ab18a181'},TOYOTA,HIACE,DX,Mini Bus High Roof,4,2015,thirdparty,JTFHX02P7F0094323,48400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '685944995d8bb5f0ab18bafc'},TOYOTA,HILUX,DL,Pick Up Double Cab,4,2015,comprehensive,JTFHXDGP7F0094373,37800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '68596237e6bdae3db611dab9'},INFINITI,QX50,LUXE STYLE,SUV,4,2024,thirdparty,JN1ASNYC3PU200564,142000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '685bb1456ce98addfc08ed19'},BMW,420I,M SPORT PREMIUM,COUPE,4,2024,thirdparty,WBA11AP04RCR41747,156500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674107,{'$oid': '6a193215019e32974c5e3521'},TOYOTA,HILUX,SGLX,Pick Up Double Cab,4,2024.0,comprehensive,None,86400.0,...,[],NaN,"{'vinDecoding': {'admeid': 34857, 'description...",NaN,NaN,1.0,False,False,False,False
1674108,{'$oid': '6a19321b019e32974c5e355d'},MG,GT,LUXURY,SEDAN,4,2022.0,comprehensive,None,37810.0,...,[],NaN,None,NaN,NaN,1.0,False,False,False,False
1674109,{'$oid': '6a19324e7ecc40bc38f32d6a'},HYUNDAI,TUCSON,GL,SUV,4,2020.0,comprehensive,None,38880.0,...,[],NaN,"{'vinDecoding': {'admeid': 25968, 'description...",NaN,NaN,1.0,False,False,False,False
1674110,{'$oid': '6a1932558c9b2a52642e77d1'},FORTHING,T5 EVO,EXCLUSIVE,SUV,4,2024.0,comprehensive,LMXA14AFXRZ354445,64644.0,...,[],NaN,"{'make': 'FORTHING', 'model': 'T5 EVO', 'year'...",NaN,NaN,NaN,False,False,False,False
1674111,{'$oid': '6a193265019e32974c5e35d2'},NISSAN,PATROL,SUPER SAFARI HT,SUV,6,2020.0,comprehensive,None,139175.0,...,[],NaN,"{'vinDecoding': {'admeid': 25961, 'description...",NaN,NaN,1.0,False,False,False,False

In [7]:
df.isnull().sum()

_id                              0
make                            23
model                            6
trim                         27134
bodyType                         3
                            ...
vehicleMileage             1508498
ocrRCVerified              1049262
ocrVCCVerified             1049262
ocrNCCVerified             1049262
ocrPassingPaperVerified    1049262
Length: 76, dtype: int64

In [11]:
df = df.astype(str)

In [12]:
df.duplicated().sum()

np.int64(0)